### ISSUE TITLE
Kills ethernet on Rpi 2 B using wifi adapter

### ISSUE THREAD

**Issue by vinay0410** [harryallerston/RPI-Wireless-Hotspot#27]
After, running this script, my hotspot is finally made. Thanks a lot for the same.
But, suddenly my ethernet dies, now I cannot use internet on my pi.
Is there a fix to solve the same.
ifconfig doesn't show an eth0.

**Comment by Fabian42** [comment]
Look at /etc/network/interfaces. Is there a line saying "wireless-power
off"? Changing that to on (and rebooting) solved the problem for me. I
don't know why it affects LAN but says "wireless", but it does.
There's also a line "auto eth0", if it's something else for you, change it
to that.
Disclaimer: I'm not sure if that fixes it 100%, I had some problems before
where LAN didn't work after every boot, but now I don't know if I still
have that problem, because my Raspberry reboots every time the LAN adapter
is disabled.

**Comment by vinay0410** [comment]
Thanks for replying.
I had no line stating ```wireless power off```. But I did have a line called ```auto lo``` and changing that to ```auto eth0``` didn't work.

Screenshots of /etc/network/interfaces file and output of ifconfig are attached below:

![screen shot 2018-03-21 at 10 54 37 pm](https://user-images.githubusercontent.com/18044818/37726615-ce026610-2d5b-11e8-9d6e-6dc6bce91666.png)
![screen shot 2018-03-21 at 10 53 24 pm](https://user-images.githubusercontent.com/18044818/37726616-cef45d76-2d5b-11e8-97ba-e878735c16e3.png)

Also, I would like to state that after running this tool by dhcpcd service was stopped, and couldn't be started. According to my experience stopping of dhcpcd service might sometimes turn of LAN.

**Comment by unixabg** [comment]
Greetings,
Could you clone and try this repository
https://github.com/unixabg/RPI-Wireless-Hotspot
 and see if all works for you? ty

**Comment by Fabian42** [comment]
Oh no, I didn't mean that line. Here's my version of the file:
# This file was installed with the RPI-Wireless-Hotspot script
# For more info see https://github.com/unixabg/RPI-Wireless-Hotspot
# ------------------------------------------------------------------------
auto lo

iface lo inet loopback
iface eth0 inet dhcp

auto eth0

auto wlan0

iface wlan0 inet static
  address 192.168.42.1
  netmask 255.255.255.0
  wireless-power on

up iptables-restore < /etc/iptables.ipv4.nat

**Comment by vinay0410** [comment]
Thanks, 
installing from https://github.com/unixabg/RPI-Wireless-Hotspot fixed my issue.
